services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile.dev
        ports:
            - 8001:8001
        volumes:
            - ./backend:/app
            - /app/node_modules
        depends_on:
            - redis
        environment:
            REDIS_HOST: redis
            REDIS_PORT: 6379
            REDIS_URL: redis://redis
    redis:
        image: redis
