services:
    voting-app:
        build:
            context: ./voting-app
            dockerfile: Dockerfile.dev
        ports:
            - 5173:5173
        volumes:
            - ./voting-app:/app
            - /app/node_modules
        depends_on:
            - redis
            - backend
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile.dev
        volumes:
            - ./backend:/app
            - /app/node_modules
        depends_on:
            - redis
        environment:
            REDIS_HOST: redis
            REDIS_PORT: 6379
            REDIS_URL: redis://redis
    redis:
        image: redis
