apiVersion: v1
kind: Service
metadata:
    name: backend-service
spec:
    selector:
        app: backend
    type: ClusterIP
    ports:
        - port: 80
          protocol: TCP
          targetPort: 80
