apiVersion: apps/v1
kind: Deployment
metadata:
    name: backend-app
spec:
    selector:
        matchLabels:
            app: backend
    template:
        metadata:
            labels:
                app: backend
        spec:
            containers:
                - name: backend-container
                  image: badi1298/backend-app
                  env:
                      - name: REDIS_HOST
                        value: redis-service.default
                      - name: REDIS_PORT
                        value: '6379'
                  resources:
                      requests:
                          cpu: 250m
                          memory: 256Mi
                      limits:
                          cpu: 500m
                          memory: 512Mi
