apiVersion: v1
kind: Service
metadata:
    name: display-app-service
spec:
    type: LoadBalancer
    selector:
        app: display
    ports:
        - port: 80
          protocol: TCP
          targetPort: 80
