apiVersion: apps/v1
kind: Deployment
metadata:
    name: voting-app
spec:
    replicas: 1
    selector:
        matchLabels:
            app: voting
    template:
        metadata:
            labels:
                app: voting
        spec:
            containers:
                - name: voting-container
                  image: badi1298/voting-app:latest
                  imagePullPolicy: Always
                  resources:
                      requests:
                          cpu: 250m
                          memory: 256Mi
                      limits:
                          cpu: 500m
                          memory: 512Mi
